seed: 42
local_epochs: 10
batch_size: 128
optimizer: sgd
lr: 0.1
momentum: 0.5
model_name: resnet18
dataset: SVHN
noise_level: 0.3
rounds: 200
num_classes: 10
num_clients: 10
ratio: 1
partition: non_iid
p: 0.7
alpha_dir: 0.5
mixup_alpha: 0.2
lc: true
mix: false
ga: false
uniform: true
proto: false

# 是否共享模型
upmodel: false

device: cuda:1

# 热启动轮数
warmup: 30

# 筛选上传原型的样本的标准
mask_mode: entropy
