seed: 42
local_epochs: 10
batch_size: 128
optimizer: adam
lr: 0.001
momentum: 0.5
model_name: resnet18
dataset: SVHN
rounds: 200
num_classes: 10
num_clients: 10
ratio: 1
partition: non_iid
p: 0.7
alpha_dir: 0.5
mixup_alpha: 0.2
lc: true
mix: false
ga: false

noise_level: 0.5
uniform: false

proto: true

# 是否共享模型
upmodel: true

device: cuda:0

# 热启动轮数
warmup: 30

# 筛选上传原型的样本的标准
mask_mode: entropy
