seed: 42
local_epochs: 1
batch_size: 128
optimizer: adam
lr: 0.001
model_name: resnet18
dataset: SVHN
noise_level: 1
rounds: 200
num_classes: 10
num_clients: 10
ratio: 1
partition: non_iid
p: 0.7
alpha_dir: 0.5
mixup_alpha: 0.2
lc: true
mix: false
ga: false
