seed: 42
local_epochs: 10
batch_size: 128
optimizer: adam
lr: 0.001
momentum: 0.5
model_name: resnet18
dataset: SVHN
noise_level: 0.3
rounds: 200
num_classes: 10
num_clients: 10
ratio: 1
partition: non_iid
p: 0.7 # 类别分布情况，值越大，那么分布越均匀
alpha_dir: 0.5 # 同一类别数量的分布情况，值越大，分布越均匀
mixup_alpha: 0.2
lc: true
mix: false
ga: false
uniform: false
proto: false
fedsa: false
upmodel: false
device: cuda:0
warmup: 30
mask_mode: entropy
fedsa_lambda_reg: 0.1
fedsa_lambda_mcl: 0.01
fedsa_lambda_cc: 1.0
fedsa_anchor_ema: 0.9999
fedsa_anchor_init_std: 1.0
